[package]
name = "code_prompter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
walkdir = "2.3"
ignore = "0.4.18"
